appName: yelearn-editor
env: beta
# web服务端口,需要同步修改前端工程配置的后台服务地址或K8s的ingress规则
server:
  port: 8081
postgresql:
  host: 120.24.24.107
  port: 5433
  user: postgres
  password: password
  dbname: earthworm
redis:
  host: 172.16.1.66
  port: 6379
  password: adminCRF123
  database: 0
  optimisation-max-idle: 100  # redis 连接池中的最大空闲连接数
  optimisation-max-active: 0 # 最大活跃连接数
gorm:
  # 控制台打印SQL
  printSql: true
  # 空闲连接池中连接的最大数量
  maxIdleConns: 10
  # 打开数据库连接的最大数量
  maxOpenConns: 100
deepSeekApi:
  baseUrl: https://api.deepseek.com
  apiKey: sk-9bd5cfe9fee74692be8bac6c514a42eb